"""add matrix routing fields

Revision ID: 4efa9e036095
Revises: 3941728edda6
Create Date: 2026-04-14 14:23:03.080848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4efa9e036095'
down_revision: Union[str, Sequence[str], None] = '3941728edda6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responders', sa.Column('dm_room_id', sa.String(), nullable=True))
    op.add_column('zones', sa.Column('matrix_room_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zones', 'matrix_room_id')
    op.drop_column('responders', 'dm_room_id')
    # ### end Alembic commands ###
