"""add responder matrix_user_id

Revision ID: a84df04cb272
Revises: f9eb07c37d06
Create Date: 2026-04-08 17:16:37.209767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a84df04cb272'
down_revision: Union[str, Sequence[str], None] = 'f9eb07c37d06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responders', sa.Column('matrix_user_id', sa.String(), nullable=True))
    op.create_unique_constraint('uq_responders_matrix_user_id', 'responders', ['matrix_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_responders_matrix_user_id', 'responders', type_='unique')
    op.drop_column('responders', 'matrix_user_id')
    # ### end Alembic commands ###
