"""add_responder_capability_toggles

Revision ID: f9eb07c37d06
Revises: 25d065bf563f
Create Date: 2026-04-07 22:14:00.039809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9eb07c37d06'
down_revision: Union[str, Sequence[str], None] = '25d065bf563f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'responders',
        sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('false'))
    )
    op.add_column(
        'responders',
        sa.Column('can_dispatch', sa.Boolean(), nullable=False, server_default=sa.text('false'))
    )
    op.add_column(
        'responders',
        sa.Column('can_respond', sa.Boolean(), nullable=False, server_default=sa.text('true'))
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responders', 'can_respond')
    op.drop_column('responders', 'can_dispatch')
    op.drop_column('responders', 'is_admin')
    # ### end Alembic commands ###
